---

- name: check to see whether neofetch already exists
  stat:
    path: "{{ neofetch_prefix }}/bin/neofetch"
  register: neofetch_stat

- name: get current neofetch version
  shell:
    cmd: "{{ neofetch_prefix }}/bin/neofetch --version | awk '{print $2}'"
  register: neofetch_current_version
  failed_when: false
  when: neofetch_stat.stat.exists

- name: install neofetch
  include_tasks: install.yml
  when: "not neofetch_stat.stat.exists or neofetch_current_version.stdout != neofetch_version"
