---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7_instance
    image: centos:7
  - name: ubuntu_bionic_instance
    image: ubuntu:18.04
  - name: ubuntu_disco_instance
    image: ubuntu:19.04
  - name: debian_stretch_instance
    image: debian:stretch
  - name: debian_buster_instance
    image: debian:buster
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
